codecov:
  notify:
    require_ci_to_pass: yes

coverage:
  status:
    project:
      default:
        threshold: 5%
    patch:
      default:
        target: 80%
        threshold: 0%

ignore:
  - "test"
